import React, { useState } from 'react'
import Head from 'next/head'
import Navbar from './components/Navbar'
import Presentation from './components/Presentation'
import HeroSection from './components/HeroSection'
import Skills from './components/Skills'
import CV from './components/CV'
import Contact from './components/Contact'
import Footer from './components/Footer'

export default function Home() {
  const [isDark, setIsDark] = useState(false)

  return (
    <div>
      <Head>
        <title>RINCON BRAZILLIER Johan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={isDark ? 'dark' : ''}>
        <div className='dark:bg-slate-900 dark:text-white'>

          <div>

            <button className='m-2 top-0 right-0' onClick={() => !setIsDark(!isDark)}>{isDark ? <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" /></svg> : <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" /></svg>}
            </button>
          </div>




          <Navbar />
          <HeroSection />
          <Presentation />
          <Skills />
          <CV />
          <Contact />
          <Footer />
        </div>
      </main >
    </div >
  )
}
